### ISSUE TITLE
Geen right edge with FDC

### ISSUE THREAD

**Issue by kubrickfr** [ILiebhardt/darktable#6]
it's particularly visible if dark picture with boosted exposure:
![image](https://user-images.githubusercontent.com/2634188/27836728-a2c9c420-60d8-11e7-8c93-43ff8c2cbc2a.png)

It's 6px wide and actually contains a non-null value for red and blue.

**Comment by ILiebhardt** [comment]
Ah, I think I already know where this one is coming from. I bet it wasn't there when the initial filters were still implemented as nested loops. Switching to fftw introduced an asymmetricity to the right and to the bottom, six pixels each. It should be possible to solve this by more padding I think. Do you also have this effect at the bottom? Thx, I

**Comment by kubrickfr** [comment]
No, bottom is fine. I tried increasing the padding but maybe not enough. I think it's more likely another issue as cropping just one px on the right gets rid of the problem.

**Comment by ILiebhardt** [comment]
You're right. It's not what I first thought. Strangely enough I don't manage to reproduce it, not even with very dark images, boosting exposure a lot.

**Comment by kubrickfr** [comment]
What is your camera? Mine is an X-T2. I don't know if it matters but with this model TS is a divider of the frame width...

**Comment by ILiebhardt** [comment]
Mine are x-pro1 and x100s - no problem. But I received an x-t2 image from a darktable development mailing list member who helped me testing and there (!!!) I can reproduce it. Right border indeed.

**Comment by ILiebhardt** [comment]
OK, I found out something at least. This was already present when the convolution filtering was still implemented as nested loops. So this is not a consequence of the introduction of fftw. It is also not the problem that the image width is a multiple of TS. Further searching required, I'm afraid...

**Comment by ILiebhardt** [comment]
Should be solved now. But I'm not entirely happy with it; this should not have been necessary in theory... I'll still look for a better solution.

**Comment by kubrickfr** [comment]
That's indeed very weird, I wonder if it could be an issue with rawspeed... Maybe we should report / investigate it as such?
Also, with this edit https://github.com/ILiebhardt/darktable/commit/bdacef284399a8bf53506f0a5a415f108282b113#diff-a001a1125b3a87d818accabc8b2f2751R1628 you should probably get rid of the median calculation altogether, right?
