### ISSUE TITLE
Without median filtering, diagonal lines appear

### ISSUE THREAD

**Issue by kubrickfr** [ILiebhardt/darktable#8]
Markesteijn:
![20170604_0174](https://user-images.githubusercontent.com/2634188/28261679-20941546-6ad8-11e7-9261-66e39c42038c.jpg)
FDC with median filtering:
![20170604_0174_01](https://user-images.githubusercontent.com/2634188/28261710-4095dc4e-6ad8-11e7-98dd-4747fb0ce9bd.jpg)
FDC without median filtereing (current head):
![20170604_0174_02](https://user-images.githubusercontent.com/2634188/28261727-4f9e28ea-6ad8-11e7-9815-e172bea54899.jpg)
You can see in the leaves darker diagonal lines.

Raw file: https://drive.google.com/open?id=0ByPjAhK7ObclMURNdHhkazNQc2M

**Comment by kubrickfr** [comment]
A view of the difference, a regular pattern definitely emerges:
![untitled](https://user-images.githubusercontent.com/2634188/28264076-33b465e6-6ae1-11e7-9d59-25e8ef2c7233.png)

**Comment by kubrickfr** [comment]
Unsurprisingly, the same problem appears for blue-saturated areas, with the diagonals being at a 90° angle from the red pattern.

We clearly see the X trans pattern appearing:
![image](https://user-images.githubusercontent.com/2634188/28265975-69986df2-6aea-11e7-9540-db38d2174748.png)

**Comment by kubrickfr** [comment]
Very distracting example (90° rotated), tell me if you need the RAW file.
![image](https://user-images.githubusercontent.com/2634188/28317825-66cb1c1a-6bc0-11e7-9da4-5c61c8fde313.png)

**Comment by ILiebhardt** [comment]
Ah, this is not new to me. At least one round of median filtering is required. The only alternative you might want to try is if a 3x3 median is enough. It _is_ possible to design the four initial filters such that no median at all would be required, but then you'd get other unwanted side-effects such as very pronounced colour bleeding and a less agile colour response. Been there, done that ;-)

**Comment by kubrickfr** [comment]
I'm not saying your wrong, but I really would like to understand.
I think I understand the trade-off your talking about, but what I don't understand and therefore what looks like a bug to me is: considering that that 4 fftw filters you're talking about are applied _after_ a simple interpolation is done (and therefore the structure of the CFA should not be relevant any more, for all that matters it could be bayer?), how comes we see artifacts appear that follow the x-trans pattern?

**Comment by kubrickfr** [comment]
Also, if you could share with me or document how you train the filters, I think it would help me understand your choices. It's always good if more than one persone knows what's going on.

**Comment by kubrickfr** [comment]
Also, I've reduced the median filtering to 5 pixels and I really don't see any reason to go over that, might be a matter of taste but I think bigger does more harm than good, it's enough to remove artifacts and if you feel like there is too much colour noise, you can use one of the denoise modules.
`            float temp [5];
            memcpy(&temp[0], fdc_chroma + chrm*TS*TS + (row-1)*TS + (col-0), 1*sizeof(float));
            memcpy(&temp[1], fdc_chroma + chrm*TS*TS + (row)*TS + (col-1), 3*sizeof(float));
            memcpy(&temp[3], fdc_chroma + chrm*TS*TS + (row+1)*TS + (col-0), 1*sizeof(float));
            cbcr[chrm] = quick_select(temp);`

**Comment by ILiebhardt** [comment]
Five pixels looks fine indeed, thanks a lot! :-) The training is described in on of the documents I cite in my blog. No secret at all. It's based on the least square minimum error approach, nothing fancy. And then I take reference images from the so called McMaster reference image set. Can be found googling. I noticed that there's one of a tailor's atelier with gray cloth, which makes filters broader, so I give a different weight to it.

**Comment by ILiebhardt** [comment]
Ah, but I see the misunderstanding in your above comment. The four filters are not applied after a simple interpolation. The four filters are applied directly on the raw image, and the sensor layout does play a profound role at this point. Actually I perform two complete demosaicking operations, and then I take the output of one of them for luma and directionality, and I take the output of the other one for chroma.

**Comment by ILiebhardt** [comment]
OK, and with a five pixel median, I'd like to stick with the four filters as they are... It's indeed also a matter of personal taste, and here I prefer avoiding artifacts. Definitely.

**Comment by ILiebhardt** [comment]
Aha, found it back, the filter training is described in Brian Leung, Student Member, IEEE, Gwanggil Jeon, Member, IEEE, and Eric Dubois, Fellow, IEEE 'Least-Squares Luma-Chroma Demultiplexing
Algorithm for Bayer Demosaicking', especially page 2 section B. By the way, I gave in and made them a tiny bit narrower, but that's as far as I'd go ;-). One could optimise forever, but I would now rather make a clean version to contribute. Compared with all alternatives, this one's still looking preferable I think.

**Comment by kubrickfr** [comment]
I think you nailed it in the latest revision. I'm happy with the new compromise, works great for me, thanks!

**Comment by ILiebhardt** [comment]
Thanks a lot to you, too. You helped me a couple of times when I was really blocked... next thing for me would be to try to contribute it, so that others can use it, too.

**Comment by kubrickfr** [comment]
You're more than welcome. I'm glad I finally have a meaningful opportunity to get involved with darktable.
